# Generated by Django 5.0.6 on 2024-07-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('rc_number', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
