# Generated by Django 5.0.6 on 2024-07-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseplate',
            name='aadhar_number',
            field=models.CharField(default='Unknown Vehicle', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licenseplate',
            name='mobile_number',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licenseplate',
            name='vehicle_name',
            field=models.CharField(default='0000000000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licenseplate',
            name='vehicle_type',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
