# Generated by Django 5.0.6 on 2024-07-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face', '0002_licenseplate_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='license_images/'),
        ),
        migrations.AlterField(
            model_name='licenseplate',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
